name: imagenet_pytorch_const_cifar
hyperparameters:
  global_batch_size: 256
  data_location: /mnt/data
  arch: resnet18
  workers: 4
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  evaluate: store_true
  pretrained: True
  dataset: cifar
  download: True
records_per_epoch: 50000
searcher:
  name: single
  metric: val_loss
  smaller_is_better: true
  max_length:
    epochs: 20
entrypoint: model_def:ImagenetTrial
environment:
  environment_variables:
    - http_proxy=http://172.28.6.17:3128
    - https_proxy=http://172.28.6.17:3128
    - ftp_proxy=http://172.28.6.17:3128
    - no_proxy=localhost,127.0.0.1,gl-hpe.local,10.111.135.214,192.168.201.75